### ISSUE TITLE
qBraid-SDK migrations

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/pyqasm#12]
Migrate the following functions and classes (+ corresponding tests) from `qbraid` to `pyqasm`:

- [`depth()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/analyze.py#L67)
- [`rebase()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/decompose.py#L344) (and all associated helpers)
- [`extract_qasm_version()`](https://github.com/qBraid/qBraid/blob/da28f77c71d18ce526afd77a9eebf8bc43c00132/qbraid/programs/typer.py#L106) (don't mask "opaque")
- [`QasmStringType`](https://github.com/qBraid/qBraid/blob/da28f77c71d18ce526afd77a9eebf8bc43c00132/qbraid/programs/typer.py#L207), [`Qasm2StringType`](https://github.com/qBraid/qBraid/blob/da28f77c71d18ce526afd77a9eebf8bc43c00132/qbraid/programs/typer.py#L220), [`Qasm3StringType`](https://github.com/qBraid/qBraid/blob/da28f77c71d18ce526afd77a9eebf8bc43c00132/qbraid/programs/typer.py#L226)

- [`qasm3_drawer()`](https://github.com/qBraid/qBraid/blob/da28f77c71d18ce526afd77a9eebf8bc43c00132/qbraid/visualization/draw_qasm3.py#L459) (This function needs *a lot* of work done. We will need to refactor it to leverage the `openqasm3.ast` explicitly, and from there perhaps, limit its scope to just OpenQASM 2 strings until it is stable enough to safely begin expanding to OpenQASM 3. This could be a great issue to turn over to the broader open-source community for help.)

- [`qas2_to_qasm3()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/transpiler/conversions/qasm2/qasm2_to_qasm3.py#L103) (maybe)

Possibly more to come, but this should be a good start.

Create a dev branch for qBraid-SDK, add pyqasm as a dependency, and for each of the above functions/classes that are migrated, import/replace with the appropriate pyqasm function/class in the qBraid-SDK. Open draft PRs across the qBraid-SDK and pyqasm repos so that we can review the updates in parallel.

*Note*: If things begin to get cluttered, we may want to discuss creating `pyqasm` sub-modules to distinguish different "families" of functions / operations, e.g. `core`, `typing`, `passes`, etc. But we also don't want to do so pre-maturely, before the project has had a chance to gain it's footing. Otherwise we may set ourselves up for re-factors early on, which we don't want.

In `qbraid-qir[qasm3]` we plan to maintain the dependency open `openqasm3[parser]` even after we integrate `pyqasm`. By contrast, the ultimate goal that this issue begins to work towards is to move `openqasm3` from a core to an optional dependency within the qBraid-SDK, and to replace any critical functionality implemented using `openqasm3` with equivalent out-of-the-box functionality provided via `pyqasm`.

For example, we hope to eventually refactor bloated logic surrounding calculations of number of qubits / classical bits in [`OpenQasm2Program`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/programs/gate_model/qasm2.py#L33) and [`OpenQasm3Program`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/programs/gate_model/qasm3.py#L44) and move streamlined versions of these functions into `pyqasm`. We hope to eventually remove functions like [`unfold_qasm2()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/unfold.py#L83) and replace them with simple calls to `pyqasm.unroll()`. Similarly, we hope to replace functions like [`decompose_qasm2()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/decompose.py#L124) with `pyqasm.rebase()` from the function linked above (pending migration). Eventually, we would like to dissipate all of [`qbraid.passes`](https://github.com/qBraid/qBraid/tree/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes), and sort these functions into appropriate modules, handlers, and/or helpers in `pyqasm` or within the qBraid-SDK.

Pending candidate functions up for migration may also include:

- [`has_measurements()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/analyze.py#L41)
- [`remove_measurements()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/compat.py#L299)
- others? (TBD)

> [!IMPORTANT] 
> Amidst all of these migrations, we want to be careful to *only* migrate things into `pyqasm` which are **generic** enough to also be useful to a "3rd party". Any helpers that provide functionality that is noticeably **specific** to `qbraid`, we should instead look to re-locate / reorganize somewhere else within the qBraid-SDK, wherever it is best suited.

The "ethos" of this project, in my mind, is to offer a concise, focused, and well-documented set of highly practical functions and methods to help users analyze and interface with OpenQASM programs. Overall, the package should be lightweight, fast, straightforward, user-friendly, and clear in both its purpose and utility. Anything that detracts from that, we leave out.

**Comment by TheGupta2012** [comment]
Breaking this off into several sub-issues as the PR #49 is getting pretty big.

**Comment by TheGupta2012** [comment]
- I'm a little skeptical about the development of an in-house `qasm3_drawer` as, once unrolled, the program can be easily visualized by the qiskit drawer which has become a lot more robust. 
- Maybe we can think of visualizing some higher level representation instead of the qubit level that gives a better sense of how the program is evolving. I'm coming from a place where looking at the circuit level drawing I can not understand what the program "is doing". 
- A functional-level or a basic block level drawer would be much more useful which highlights "what a particular block of quantum instructions are doing" rather than just being present as a circuit, which is hard to interpret.
- It could start off as a simple "highlighter" where in we take the quantum circuit representation and demarcate what is the "use" of a block of circuit operations. 
- Eg. - 
![Screenshot 2024-10-30 at 1 19 30 PM](https://github.com/user-attachments/assets/b642772b-8cf1-45b2-8ba4-7983586c7239)
- @ryanhill1 let me know if this is something which you think would worth exploring. As you mentioned, it'll be nice to see the open-source community pitch in on this.

**Comment by TheGupta2012** [comment]
Turns out qiskit's drawer already supports something like this - 

```python
import qiskit 

print(qiskit.__version__) 
# 1.2.0 
 
program = """
    OPENQASM 3.0;
    include "stdgates.inc";
 
    input float[64] a;
    qubit[3] q;
    bit[2] mid;
    bit[3] out;
 
    let aliased = q[0:1];
 
    gate my_gate(a) c, t {
      gphase(a / 2);
      ry(a) c;
      cx c, t;
    }
    gate my_phase(a) c {
      ctrl @ inv @ gphase(a) c;
    }
 
    my_gate(a * 2) aliased[0], q[{1, 2}][0];
    measure q[0] -> mid[0];
    measure q[1] -> mid[1];
 
    while (mid == "00") {
      reset q[0];
      reset q[1];
      my_gate(a) q[0], q[1];
      my_phase(a - pi/2) q[1];
      mid[0] = measure q[0];
      mid[1] = measure q[1];
    }
 
    if (mid[0]) {
      let inner_alias = q[{0, 1}];
      reset inner_alias;
    }
 
    out = measure q;
"""
circuit = qiskit.qasm3.loads(program)
circuit.draw("mpl")
```

Output - 

![Screenshot 2024-11-19 at 10 59 56 AM](https://github.com/user-attachments/assets/ba714efe-c999-45dd-9e99-e913481ab06b)
