### ISSUE TITLE
pyqasm.unroll return type

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/pyqasm#24]
Instead of returning a `Qasm3Module` I think it would be better if `pyqasm.unroll` just returned the unrolled qasm string directly

**Comment by TheGupta2012** [comment]
Comment [link from PR discussion](https://github.com/qBraid/pyqasm/pull/23#discussion_r1804135492) 

We can continue the conversation here

**Comment by TheGupta2012** [comment]
Fixed by #28
