### ISSUE TITLE
[FEATURE] Preserve QASM version

### ISSUE THREAD

**Issue by TheGupta2012** [qBraid/pyqasm#36]
### Feature Description

The qasm version passed by the user should be preserved but we are forcing it to be 3 and changing the representations of equivalent constructs - 

```python
In [5]: pyqasm.unroll("""
   ...: OPENQASM 2.0;
   ...: qreg q[4];
   ...: """)
Out[5]: 'OPENQASM 3;\ninclude "stdgates.inc";\nqubit[4] q;\n'
```

### Implementation (Optional)

One thing to note is that we need to identify which constructs are correctly supported by v2 and NOT by v3. This is because `openqasm3` parser does not raise exception for, say, - 
```python
import pyqasm 

In [8]: pyqasm.unroll("""
   ...: OPENQASM 2.0;
   ...: qubit[4] q;
   ...: def hello(int[32] a) {
   ...:     int[32] b =  a + 1;
   ...:     return;
   ...: }
   ...: h q;
   ...: """)
Out[8]: 'OPENQASM 3;\ninclude "stdgates.inc";\nqubit[4] q;\nh q[0];\nh q[1];\nh q[2];\nh q[3];\n'
```

Depending on the version, we should - 
1. Check which statements are valid or not 
2. Unroll in the syntax supported by that major version

**Comment by ryanhill1** [comment]
Correct, this was also a problem in [`qbraid.passes.qasm.rebase()`](https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/decompose.py#L344) which we patched temporarily by adding the following code to the end:

https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/decompose.py#L400-L406

where `declarations_to_qasm2()` is defined as follows:

https://github.com/qBraid/qBraid/blob/0ef7714d7a75ffe7aaefda0e0f1ae55611250ce0/qbraid/passes/qasm/compat.py#L248-L255

**Comment by ryanhill1** [comment]
The solution to this problem should leverage this could leverage the code we already have written in the qBraid-SDK and become a part of https://github.com/qBraid/pyqasm/issues/12

**Comment by TheGupta2012** [comment]
Yep, the code for replacing declarations is pretty useful. 
Also found a kwarg in `openqasm3.dumps` which lets us force the measurement to be in qasm2 format, so some effort saved there!
