### ISSUE TITLE
[FEATURE] `pyqasm` CLI: analyze command, similar to prettier

### ISSUE THREAD

**Issue by ryanhill1** [qBraid/pyqasm#51]
Introduce a command-line interface (CLI) for `pyqasm` with an "analyze" command that validates and optionally auto-fixes OpenQASM programs (when possible), similar to the prettier tool used for formatting code.

Can be included as project dependency "extra",  or as a new package entirely.

For example:

```bash
$ pip install pyqasm[cli]
```

```bash
$ pyqasm analyze program.qasm
1 Error, 2 Warnings

Error [Line 6, Column 4]: Qubit index is out of range (used index 3, but only 2 qubits are defined)

Warning [Line 8, Column 10]: Unused classical register 'c_reg' declared but not referenced

Warning [Line 10, Column 2]: Barrier instruction is redundant in this context

Suggestion: Run with '--fix' to automatically resolve the error

1 Error potentially fixable with --fix command
2 Warnings require manual review
```

And the `--fix` command could look something like:

```bash
$ pyqasm analyze program.qasm --fix

Fix applied: Updated Qubit index at Line 6, Column 4 (corrected to index 1)

1 Warning still remains: Unused classical register 'c_reg'

Program updated and formatted.

$ pyqasm analyze program.qasm
1 Warning

Warning [Line 8, Column 10]: Unused classical register 'c_reg' declared but not referenced

Tip: Consider removing the unused classical register to improve readability
```

Recommendation would be build this CLI extension using [Typer](https://typer.tiangolo.com/), which is what we use for the [qBraid-CLI](https://docs.qbraid.com/cli/user-guide/overview).

Or, could simply bring `pyqasm` in as a dependency extra to the qBraid-CLI to enable this same functionality e.g.

```bash
$ pip install qbraid-cli[pyqasm]
```

```bash
$ qbraid pyqasm analyze program.qasm
```

Would use a better convention for the commands, but you get the idea.

**Comment by TheGupta2012** [comment]
I think if we are projecting `pyqasm` as more of an independent tool for community, it would be better to go ahead with the dependency "extra" approach.
