### ISSUE TITLE
[FEATURE] Decompose branching statement containing `bit` register

### ISSUE THREAD

**Issue by TheGupta2012** [qBraid/pyqasm#52]
### Feature Description

`openqasm3` supports branching statements of the form - 
```c
...
qubit[3] q; 
h q; 
bit[3] c; 
c = measure q; 
if (c == 4) { ... }
``` 
where `c` is a 3 bit classical register. Currently, `pyqasm` only supports unrolling [single bit measurement results](https://github.com/qBraid/pyqasm/blob/main/tests/qasm3/test_if.py#L57) but we aim to support unrolling of this shorthand notation. 

The motivation for this feature is to enable program execution for QC vendors which only supports single bit level branches. Using the above, a generic register comparison can be unrolled to "cascaded" single bit branching statements and, thus, run on the system. 

### Implementation (Optional)

- The comparison can be divided into 3 broad categories - `==`, `>=` and `<=`. 
- Register comparisons will be something like `if (c == 6) { // execute this block of statements}`.
- Whenever a "full register" is encountered in the branching statement we do the following - 
    - Get the size of the register ,say, `4`
    - Represent the RHS i.e. `6` in `4` bits - `0110`
    - For each bit of the register, compare the corresponding bit of the RHS - 
   
        ```c
           if (c[0] == 0) 
           {  if (c[1] == 1) 
              {  if (c[2] == 1) 
                 {  if (c[3] == 0) 
                      { // execute this block } 
                  }
               }
            }
          ```
    - `==` can be replaced with `>=` or `<=` for the respective binary operator 
- Major chunk of processing would be done in [`_visit_branching_statement` method](https://github.com/qBraid/pyqasm/blob/d77251c24e9f744a40ab6a5363dbb891c976c850/pyqasm/visitor.py#L1071) of the visitor module. 
- Essentially, we just construct a new `if_block` for the branching statement which will contain these cascading if conditions. The last `if_block` will contain the block of statements

**Comment by arulandu** [comment]
Interested in working on this! Will open a PR after making some progress
