### ISSUE TITLE
[FEATURE] Add support for parsing `not` gate

### ISSUE THREAD

**Issue by TheGupta2012** [qBraid/pyqasm#68]
### Feature Description

The qasm - 
```c 
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
not q[1];
``` 
should be correctly parsed but raised an error - 

```bash
ValidationError: Unsupported / undeclared QASM operation: not
```
We should add the alias for it in `maps.py` and apply the `x` gate whenever it is encountered

**Comment by arulandu** [comment]
Can I get assigned to this?

**Comment by TheGupta2012** [comment]
Yep, was added in an earlier PR, forgot to add a back-ref. Thanks for highlighting!
